<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-GROHIM38" failures="1" tests="2" name="Test" time="33.714" errors="0" timestamp="2021-12-21T13:51:05 IST">
  <testcase classname="com.qa.tests.BholaPhonesTest" name="signInNegative" time="5.413">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.tests.BholaPhonesTest.signInNegative(BholaPhonesTest.java:43)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- signInNegative -->
  <testcase classname="com.qa.tests.BholaPhonesTest" name="signInPositive" time="6.802"/>
</testsuite> <!-- Test -->
